all:
	gcc main.c conversion.c motors.c solve.c search.c facecube.c cubiecube.c coordcube.c -o rubik -Wall -Werror -g

run:
	echo "UUUUUUUUUBBBRRRRRRRRRFFFFFFDDDDDDDDDFFFLLLLLLLLLBBBBBB" | ./rubik

clean:
	rm -f rubik
